apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-config"
data:
  FHIR_SERVER_URL: "{{ .Values.backend.fhirServerUrl }}"
  JWT_ALGORITHM: "{{ .Values.backend.jwtAlgorithm }}"
  JWT_EXPIRE_MINUTES: "{{ .Values.backend.jwtExpireMinutes }}"
  LOG_LEVEL: "{{ .Values.logLevel }}"
